apiVersion: v1 
kind: Pod
metadata:
  name: labels 
  annotations: 
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.joindevops.com/expense/backend/build/67"

spec:
  containers:
  - name: nginx
    image: nginx
