apiVersion: v1 
kind: pod
metadata:
  name: environment 
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        value: devops
      - name: duration
        value: "120hrs"
