apiVersion: v1 
kind: pod
metadata:
  name: resource 
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 60Mi
      limits:
        cpu: 120m
        memory: 100Mi