apiVersion: v1 
kind: pod
metadata:
  name: pod-config 
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapKeyRef:
        name: nginx-config
      
    # env:
    #   - name: course
    #     valueFrom:
    #       configMapKeyRef:
    #         name: nginx-config
    #         key: course
    #   - name: duration
    #     valueFrom:
    #       configMapKeyRef:
    #         name: nginx-config
    #         key: duration