kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    ports: 80 # service port
    targetport: 80 # container port